### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by edwardmp**
hi @ShadyBoshra2012,

Am back again with a few updates

* I upgraded the Checkout SDK to latest version
* Add methods to be able to tokenise Google and Apple Pay data
* Everything should be backwards compatible

### CODE REVIEW

**Review by ShadyBoshra2012 — APPROVED** [review]
Thanks @edwardmp for your contribution, I approved it, but you have to know that I don't have time to test it, so I depend on your testing. If you see everything is going well, please merge it and I will release new version on pub.dev

**Comment by edwardmp** [comment]
Hi @ShadyBoshra2012 

Understood! We are actually already shipping with these changes, so I'm pretty confident they don't wreak havoc ;)

**Comment by ShadyBoshra2012** [comment]
Thanks again @edwardmp , the package is published with version 1.3.0

**Comment by ShadyBoshra2012** [comment]
I think it will work as it refered to the path of package not its version

```
flutter_checkout_payment:
    path: ../
```

**Pull request merged**
