### PR TITLE
Add threeds handling

### PR DESCRIPTION
**Pull request by edwardmp**
Hi @ShadyBoshra2012 

Thanks for making this plugin. I recently used it, but noticed the plugin doesn't support 3DS handling yet  (see https://www.checkout.com/docs/integrate/sdks/ios-sdk#Handle_3D_Secure).

So I implemented it, I also bumped the version to 1.1.

Only thing I'm not sure of: how to update the /docs directory, do you have a script for this?

Let me know, hope we can merge this in asap!

### CODE REVIEW

**Comment by ShadyBoshra2012** [comment]
Thanks @edwardmp for your contribution ❤️, I will check it next week and confirm with you.

If there's any updates please let me know anytime.

**Comment by edwardmp** [comment]
Hi @ShadyBoshra2012 did you have some time to check it out?

**Comment by ShadyBoshra2012** [comment]
Thanks @edwardmp for your contributing, I merged your PR to dev branch, and I will enhance some code arround, then I will make new release for the package.

**Comment by ShadyBoshra2012** [comment]
It has been published by now, thanks for your contributing @edwardmp, I mentioned you in the package README. ❤️

**Comment by edwardmp** [comment]
@ShadyBoshra2012 awesome, thank you too! ❤️

**Pull request merged**
